### ISSUE TITLE
[Research] Verify one state transition by S[N|T]ARKS

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#113]
## Description

Research it is effective or not by using zkSTARKs for one state transition in TxVerification. (like semaphore or miximus)

- The state will become small?
- Does it reduce the verification cost of big state transition?

Please imagine the lottery or vote which many people participate.
If a hundred people vote with a UTXO, the state becomes big for a voted bit. And calculation cost becomes expensive in exit scenario. It's like L3. We wanna know whether zkSTARKs can solve this problem or not.

### References

- https://github.com/HarryR/ethsnarks

**Comment by syuhei176** [comment]
<img width="698" alt="2018-11-29 10 40 29" src="https://user-images.githubusercontent.com/1094660/49193662-38af8780-f3c3-11e8-9c18-67d8a3347a4f.png">

**Comment by shogochiai** [comment]
I guess that naming would be matter when the L3 sidechains come.

But I can get what you depicted above.

**Comment by shogochiai** [comment]
If we call `UTXO` as `ContractState`, and `Tx` as `transit()`, then the `L2:PlasmaChain` is gonna be the set of `transit(ContractState, Bytes):ContractState` functions.

Let's say we can regard `ContractState(=UTXO)` as like the `Contract` in the EVM.

In `L2:PlasmaChain`, there're many `Contracts` in it, and then these `Contracts` consist certain application. So, I would like to call `UTXO` as `ContractState in L2` rather than `L3:UTXO`

**Comment by shogochiai** [comment]
ContractState is consisted by
- label: Like contract address in EVM
- values: Set of Value. And the Value is segment of Plasma Prime.
- state: Binary state. The ContractState which label is 0 - has this field. `transit()` function have label based pattern matcher, and state would be verified at there.

**Comment by syuhei176** [comment]
Oh, you right. I think It's a real L2 contract as UTXO.

**Comment by shogochiai** [comment]
AFAIK, Zilliqa's SCILLA and Tezos's Liquidity always return storage as output. Maybe because they have type checker for storage.

Chamber lang is also able to have such one maybe. (Sorry for off topic from zkp)

**Comment by shogochiai** [comment]
Maybe obsoleted. If important, please warmly remake issue.
