### ISSUE TITLE
History transfer <2sec

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#116]
Fast Finality may aim 2sec Tx. This is minimum experience criterion of current payment system. I guess the history transfer would be the technical bottleneck especally one of participant is under the poor connection.

**Comment by shogochiai** [comment]
@syuhei176 any overwrapping issue/PR?

**Comment by syuhei176** [comment]
I think this is out of dated. We sure to have more concrete issues.
