### ISSUE TITLE
Mapping between integer and prime

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#130]
## Description

We need a mapping between coin and prime on root chain.

ex solution) https://ethresear.ch/t/primehash-game-for-plasma-prime/4103

**Comment by syuhei176** [comment]
In our code, each coin struct has a prime number.
We can check inclusion and exclusion using this information.
And anyone can challenge this prime number by prime hash game.
https://github.com/cryptoeconomicslab/plasma-chamber/blob/master/packages/chamber-rootchain/contracts/RootChain.sol#L66

**Comment by syuhei176** [comment]
We can use Merkle Tree that leaves are prime numbers.
The root of 2^40 prime numbers tree is always same.
Anyone can make proof.

https://ethresear.ch/t/log-coins-sized-proofs-of-inclusion-and-exclusion-for-rsa-accumulators/3839

**Comment by shogochiai** [comment]
Genius idea!

**Comment by syuhei176** [comment]
Yeah, from this thread.
https://research.cryptoeconomicslab.com/t/topic/241/2

**Comment by shogochiai** [comment]
RSA Accumulator has been postponed and we use checkpoint
