### ISSUE TITLE
Add standard library

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#15]
## transfer

change owner of value.

- input: OwnState
- args: NewOwner
- output: OwnState

## exchange

exchange values.

- input: [OrderBookState, OwnState]
- args: []
- output: [OwnState, OwnState]

### OrderBookState

- assetId
- amount

## simple multisig

- input: [OwnState(owners=[A]), OwnState(owners=[B])]
- args: []
- output: [OwnState(owners=[A, B])]

## multisig

- input: [OwnState(owners=[A]), OwnState(owners=[B])]
- args: [minUnlocksigs, refundTime]
- output: [MultiSigState(owners=[A, B])]

### MultiSigState

- minUnlocksigs
- owns[]
  - owner
  - value
- refundTime

**Comment by shogochiai** [comment]
Similar discussion: Example Preparation
https://github.com/cryptoeconomicslab/plasma-chamber/issues/29#issuecomment-430835196

**Comment by shogochiai** [comment]
I guess template has been added. I close this issue for now.
