### ISSUE TITLE
share history in multiple devices

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#150]
## Description

SMT -early or mid 2019-> RSA accumulator -after 2019->START based

it will take time to get a solution of trusted setup.

I propose the feature to share history in multiple devices which the user permit. I assumed that share between PC and mobile or share among with the family devices.

**Comment by shogochiai** [comment]
zcash's snark trusted setup was 5person setup. At least a participant if discarded secret, admin role has to be abandoned. (Unless all 5 people compromised, It's okay)

**Comment by syuhei176** [comment]
This is very future work. So close now.
