### ISSUE TITLE
Commit Aggregation Service

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#158]
## Purpose

When an operator wanna increase the total deposit amount, they can use large Merkle tree.
However, when the operator wanna reduce gas cost, only they have to do is make block time longer.
By commit aggregation, operators reduce their gas cost.

## Solution

Operators have Merkle root of their plasma chain. Operators sign Merkle root and send it to hub service. The hub makes 2nd level Merkle tree from Plasma Chain's merkle root. The hub submit to main chain.

Withholding scenario and invalid block scenario is same as normal exit-game.

**We should care about which operator and hub should be penalized.**

TBD

## aggregation SaaS

Each operator pays fee to the hub and sends their Merkle root.
This is web API.
But hub and operator should be penalized in the invalid scenario, so we need setup phase.

**Comment by shogochiai** [comment]
Postpone until [Litigable Protocol](https://scrapbox.io/cryptoeconomicslab/Litigable_Protocols) get to be popular
