### ISSUE TITLE
Proof of the safety of exit-game

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#159]
isabelle

**Comment by shogochiai** [comment]
In Chamber and Prime, we call it callenge game maybe?

**Comment by syuhei176** [comment]
challenge game is part of exit game.

**Comment by shogochiai** [comment]
🤔
https://twitter.com/_julesh_/status/1102635801630990336?s=19

**Comment by shogochiai** [comment]
Proving is difficult but inductive listing of malicious exits will help mitigate the risk of remaining unchallengeable exit.

**Comment by shogochiai** [comment]
Inherit to https://github.com/cryptoeconomicslab/plasma-chamber/issues/230
