### ISSUE TITLE
Plasma block checkpoint

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#161]
## Purpose

To reduce history.
Users don't have to verify history before the checkpoint.

## Description

The checkpoint is the state Merkle root. Operator store bit field on the main chain which represents signatures coin holders confirm checkpoint. We can use checkpoint as deposit block.

**Comment by shogochiai** [comment]
Quick Note

1. How the block amount between two checkpoints will be?
-> Coin holders amount will be maximally slot count. Let's say 2^40. Do the participants need to wait unanimous ballots?

2. Just after Commit Aggregation Hub information updated,  *Must* the affected Plasma make checkpoint just after updating event?
