### ISSUE TITLE
Gasless Exit via GasStationNetwork

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#233]
Meta transaction based gas-concealed Deposit/Exit/Challenge.
This maximize usability of stablecoin based Plasma.
http://eips.ethereum.org/EIPS/eip-1613

**Comment by syuhei176** [comment]
Research task should be moved to [publication](https://github.com/cryptoeconomicslab/publications) or [research](https://github.com/cryptoeconomicslab/research)
