### ISSUE TITLE
✨ Docker Compose ✨

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#245]

**Comment by syuhei176** [comment]
I hope that docker compose up launch ethereum client(include contract), child chain and wallet😄

**Comment by shogochiai** [comment]
I'm inviting @wshino

**Comment by wshino** [comment]
🙆‍♂️

**Comment by syuhei176** [comment]
related to https://github.com/cryptoeconomicslab/plasma-chamber/issues/305
