### ISSUE TITLE
searchUTXO can be null for certain condition

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#260]
**Describe the bug**
When you send Tx on [wallet](https://plasma-chamber-demo1-m.cryptoeconomicslab.com/transfer/) with almost-all amount of your balance, error shows "too large amount" error.

**To Reproduce**
1. Go [wallet](https://plasma-chamber-demo1-m.cryptoeconomicslab.com/transfer/)
2. Deposit 1000DAI
3. Send 501DAI to someone other and confirm the "too large amount" error
4. Send 500DAI to someone other and confirm "Transfer succeeded" message

**Expected behavior**
Send exactly 1000DAI

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.12.6
 - Browser Brave(Chromium)
 - Version 73.0.3683.86

**Additional context**
I guess searchUTXO's [amount checker](https://github.com/cryptoeconomicslab/plasma-chamber/blob/de725336ea7bcb17db8a5c755518e1fea529b57d/packages/wallet/src/wallet.ts#L568) is wrong 

![Screen Shot 2019-04-08 at 19 12 36](https://user-images.githubusercontent.com/4891004/55716595-54423300-5a32-11e9-8353-6fbf6e97df90.png)
![Screen Shot 2019-04-08 at 19 12 45](https://user-images.githubusercontent.com/4891004/55716594-54423300-5a32-11e9-902b-3dc0c3842a98.png)

**Comment by syuhei176** [comment]
If you have multiple UTXOs. searchUTXOs can't get multiple UTXOs at same time.
And we can include 4 transfers in one transaction. ( https://github.com/cryptoeconomicslab/plasma-chamber/pull/250/files#diff-59f0a73a76f2178c3f3923472c1d08c5R233 )
So we should modify `searchUTXOs`.

**Comment by shogochiai** [comment]
Eureka! One of a usecases of Multisends is for this case!

**Comment by shogochiai** [comment]
Continue on
https://github.com/cryptoeconomicslab/plasma-chamber/issues/261
