### ISSUE TITLE
Unknown predicate name

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#279]
**Describe the bug**
`node -r dotenv/config lib/entry.js` in `packages/operator` is failed with error message "Unknown predicate name"

**To Reproduce**
1. Be in [current latest](https://github.com/cryptoeconomicslab/plasma-chamber/commit/37313163fbc423968784eea4a9246823af6927c4)
2. refresh your env
3. Run `node -r dotenv/config lib/entry.js` in `packages/operator`

**Expected behavior**
Safely run operator process

**Screenshots**
![Screen Shot 2019-04-11 at 2 00 23](https://user-images.githubusercontent.com/4891004/55898718-29a4d580-5bfe-11e9-90ad-fe9dc49a44ea.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.12.6

**Comment by shogochiai** [comment]
@syuhei176 have you confirmed this error?

**Comment by syuhei176** [comment]
please add OWNERSHIP_PREDICATE address
https://github.com/cryptoeconomicslab/plasma-chamber/pull/280

**Comment by shogochiai** [comment]
@syuhei176 
`packages/operator` also was required that change.
I added that part and made pull-req. Plz warmly review it.

https://github.com/cryptoeconomicslab/plasma-chamber/pull/283
