### ISSUE TITLE
About attacks

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#29]
## Description

We have to write up all attack potentials.

https://docs.google.com/document/d/16PW1WYmS7_pli8xQi0lbzRJZbQiAbmFnP-4wyUesGBc/edit?usp=sharing

**Comment by shogochiai** [comment]
Application Specific Attack Description is impossible so that sample dapps attack explanation is better.

And core attack is simply comes from PlasmaCash so that History DoS or something like that would be enough
