### ISSUE TITLE
Lerna versioning rule

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#292]
Current mode is `Fixed/Locked mode` and so all monorepos are same version.

If we rely on semver, as many devs make some changes, minor version will easily be conflicted with others. Fear of conflict make devs hesitate to contribute. But it discourage to make thing abstract.

Any workaround?

**Comment by syuhei176** [comment]
Sorry, another topic.
I found good module for change log.
https://github.com/lerna/lerna-changelog

CC: @daiki44

**Comment by shogochiai** [comment]
cool

**Comment by syuhei176** [comment]
And we can use `learn publish --only-explicit-updates` to publish updated modules.

**Comment by shogochiai** [comment]
But it doesn't necessarily solve conflict issue, right?

**Comment by shogochiai** [comment]
hmm, `--only-explicit-updates` is basically same as `lerna independend mode`, and it's make conflict probability lower.

Think unltimately, under an assumption that devs never forget to fetch repos before publish, and the publishing timing isn't overlap within e.g. 5min, version conflict never happens.

But sudden version bump can cause degradation of system. So, breaking change must precisely be published as major version update.

**Comment by shogochiai** [comment]
Flow chart. Codebase must be well tested for operate them.

```
lerna publish -----ok-----> Any parallel major version? -------yes-----> fetch it, fix breaking change, run test, and bump major ver ---> DONE
                    |                                           |
                    |                                           |____> DONE
                    |
                    |_fail__> conflict. fetch conflicted ver, run test, bump ver, and republish your package ---> DONE

```

**Comment by shogochiai** [comment]
Handover to #297
