### ISSUE TITLE
state transition verification library for child chain and wallet

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#328]
## Description

state transition verification library for child chain and wallet.
We would use pig's verifier.

**Comment by shogochiai** [comment]
@syuhei176 I have a motivation to try predicate and so I would like to put evm.js in this repo to instantly try&error&learn how the plapps work. Did you as well plan to do so?

**Comment by shogochiai** [comment]
I noticed I can do channel test on L1, yak shaving!

**Comment by syuhei176** [comment]
This issue is outdated. I will think other way.

**Comment by shogochiai** [comment]
Please kindly consider continuing discussion here.

https://github.com/cryptoeconomicslab/plasma-chamber/issues/338
