### ISSUE TITLE
can't learn bootstrap after clone?

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#332]
**Describe the bug**

Sorry I didn't tried yet. 
But maybe we can't access `lerna-semantic-release` before bootstrap.
https://github.com/cryptoeconomicslab/plasma-chamber/blob/master/package.json#L19

**Comment by shogochiai** [comment]
I made it `yarn install` hooks `lerna bootstrap`. Isn't it enough?

**Comment by syuhei176** [comment]
OK. So, should I `yarn install` instead of `learn bootstrap`?

**Comment by shogochiai** [comment]
yes that's right🤗
