### ISSUE TITLE
Do not pass contracts test.

### ISSUE THREAD

**Issue by nakajo2011** [cryptoeconomicslab/plasma-chamber#334]
**Describe the bug**
Run `yarn test` in packages/contracts, then got following error:
```
Error: Cannot find module '@layer2/core'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nakajo/work/ethereum-test/plasma-chamber/packages/contracts/test/Checkpoint.test.js:26:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /Users/nakajo/work/ethereum-test/plasma-chamber/node_modules/truffle/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/nakajo/work/ethereum-test/plasma-chamber/node_modules/truffle/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/nakajo/work/ethereum-test/plasma-chamber/node_modules/truffle/node_modules/mocha/lib/mocha.js:536:10)
    at /Users/nakajo/work/ethereum-test/plasma-chamber/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:135:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Truffle v5.0.12 (core: 5.0.12)
Node v8.16.0
```

**To Reproduce**
1. Run `lerna clean` on plasma-chamber/
2. Run `lerna bootstrap` on plasma-chamber/
3. cd packages/contracts
4. Run `yarn test` then see error above.

**develop environment (please complete the following information):**
 - Node: v8.16.0
 - npm: 6.9.0
 - lerna: 3.13.4
 - yarn: 1.15.2

**Comment by shogochiai** [comment]
I tried reporoducing it and confirmed the `/wallet` test cannot find `@layer2/core`.

And I know this error is also confirmed in [ref1](https://github.com/cryptoeconomicslab/plasma-chamber/issues/301#issuecomment-483978723) and [ref2](https://github.com/cryptoeconomicslab/plasma-chamber/pull/265#issuecomment-481158786).

Lerna's `--hoist` install forcibly compress the duplicating packages into monorepo's root `/node_modules`, but it somehow causes this error. Need more investigation.

**Comment by shogochiai** [comment]
I would say https://github.com/TypeStrong/ts-node/issues/234#issuecomment-259224566 is quite closer issue.

**Comment by shogochiai** [comment]
Note: `"test": "TS_NODE_COMPILER_OPTIONS='{\"moduleResolution\": \"node\"}' mocha --require ts-node/register 'test/**/*.ts'"` didn't solve this issue.

**Comment by syuhei176** [comment]
> **Describe the bug**
> Run `yarn test` in packages/contracts, then got following error:
> 
> ```
> Error: Cannot find module '@layer2/core'
>     at Function.Module._resolveFilename (module.js:548:15)
>     at Function.Module._load (module.js:475:25)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/Users/nakajo/work/ethereum-test/plasma-chamber/packages/contracts/test/Checkpoint.test.js:26:5)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at /Users/nakajo/work/ethereum-test/plasma-chamber/node_modules/truffle/node_modules/mocha/lib/mocha.js:231:27
>     at Array.forEach (<anonymous>)
>     at Mocha.loadFiles (/Users/nakajo/work/ethereum-test/plasma-chamber/node_modules/truffle/node_modules/mocha/lib/mocha.js:228:14)
>     at Mocha.run (/Users/nakajo/work/ethereum-test/plasma-chamber/node_modules/truffle/node_modules/mocha/lib/mocha.js:536:10)
>     at /Users/nakajo/work/ethereum-test/plasma-chamber/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:135:1
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:189:7)
> Truffle v5.0.12 (core: 5.0.12)
> Node v8.16.0
> ```
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Run `lerna clean` on plasma-chamber/
> 2. Run `lerna bootstrap` on plasma-chamber/
> 3. cd packages/contracts
> 4. Run `yarn test` then see error above.
> 
> **develop environment (please complete the following information):**
> 
> * Node: v8.16.0
> * npm: 6.9.0
> * lerna: 3.13.4
> * yarn: 1.15.2

@nakajo2011 
Please try `yarn build` before `yarn test`.
ps: We'll add `yarn build` command before `yarn test`.

**Comment by nakajo2011** [comment]
> @nakajo2011
> Please try `yarn build` on the root before `yarn test`.
> ps: We'll add `yarn build` command before `yarn test`.

@syuhei176 Thanks! I solved by this advice.
I guess you should modify `Getting Stated` to including this process.
