### ISSUE TITLE
Minimal Viable Predicate Sandbox

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#338]
**Motivation**
Prototyping and test running of predicate for learning purpose.

**Checklist**
- [ ] predicate plugin (if we can use evm.js by ignoring some security guarantee, we would be able to accept it for sandbox usage)
- [ ] Any other tasks?

**Comment by syuhei176** [comment]
https://github.com/cryptoeconomicslab/plasma-predicates would be good one.
