### ISSUE TITLE
Add sendTransaction API

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#35]
## Description

1. user create, sign and send transaction. (need all input owner's signatures)
2. child chain server receive transaction, and broadcast result(utxo) and proof to all output's owners.
3. client wallet store utxo and proof.

We wanna care data availability by distributed light client nodes.

**Comment by shogochiai** [comment]
> distributed light client nodes
infura/getho for plasma

**Comment by shogochiai** [comment]
The #2 is the main topic. This implies light client must have some sort of socket connection.

**Comment by shogochiai** [comment]
What if an output owner is offline and doesn't tie the socket at that publish moment?

I suggest some kinda queue or light client fetching on next online time is needed

**Comment by syuhei176** [comment]
We have to fix `sendTransaction` API, because we can't use web3's `sendRawTransaction` and `sendSignedTransaction` now.
We define original API to send transaction.

**Comment by shogochiai** [comment]
done at demo
