### ISSUE TITLE
Coin's `uid` is not incremental at Deposit

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#48]
Reference Implementation: https://github.com/loomnetwork/plasma-cash/blob/master/server/contracts/Core/RootChain.sol#L256

Truffle Test
CLI demo

**Comment by syuhei176** [comment]
This is already implemented. If it has problem, please reopen.

https://github.com/cryptoeconomicslab/plasma-chamber/blob/master/rootchain/contracts/RootChain.sol#L188

**Comment by syuhei176** [comment]
Sorry, `uid` is not incremental, so reopen this issue as bug fix issue.

https://github.com/cryptoeconomicslab/plasma-chamber/blob/master/rootchain/contracts/RootChain.sol#L194
