### ISSUE TITLE
Send Tx Demo by using CLI wallet

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#49]
- Send Tx Demo by using CLI wallet (#50 SMT creation is related)
- Write spec for Tx enabling codes

**Comment by syuhei176** [comment]
This is not task of define class? 

CLI tool is here: https://github.com/cryptoeconomicslab/plasma-chamber/tree/master/packages/chamber-cli
Send Tx from Web App example is here: https://github.com/cryptoeconomicslab/plasma-sample-app/blob/master/app/actions/index.js#L53

**Comment by shogochiai** [comment]
@syuhei176 Yeah that `sendRawTransaction()` is very good example of outcome of this issue.
The past Chamber is based on MVP so that Cash modification is the main matter. Somehow overraping with #50 though...

**Comment by shogochiai** [comment]
we did it on demo
