### ISSUE TITLE
How to get proof(and own UTXO) by wallet?

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#52]
#49 #50 have to be done beforehand

**Comment by syuhei176** [comment]
We have to the discussion about how to get proof.

1. wallet should get proof(in any case, wallet need trigger to get proof)
2. child chain should broadcast proof

**Comment by syuhei176** [comment]
I got a simple idea.
Child chain need not to broadcast.

Users always should get block they don't have.
And they create proof themselves and get their UTXOs by filtering transactions outputs.

**Comment by syuhei176** [comment]
done by this PR.
https://github.com/cryptoeconomicslab/plasma-chamber/pull/67
