### ISSUE TITLE
PlasmaCash Challenge

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#55]
1. Add type field to arg in order to classify which type of challenge is needed
2. Make condition by that type
3. Deal with challenge algo according to type

**Comment by syuhei176** [comment]
Is this issue include these all?
- SpentChallenge
- InvalidHistoryChallenge
- respondChallenge

**Comment by shogochiai** [comment]
Yup. Could we narrow down more?
