### ISSUE TITLE
PlasmaCash Withdrawal

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#56]
1. FinallizeExit and make 1 week old `exitSlots` subsets to be graduated
2. Send simple asset to the rootchain address
3. Deal with contract withdrawal (by state transition on Rootchain??)

**Comment by syuhei176** [comment]
cash model may has not `priorityQueue`.

**Comment by shogochiai** [comment]
Ah just ExitQueue.

BTW good labeling

**Comment by shogochiai** [comment]
Woa, `exitSlots `
