### ISSUE TITLE
Chamber Language Design

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/plasma-chamber#57]
State based?
Tx based?
Procedure based?
Formal verifiable?

**Comment by shogochiai** [comment]
What is the true usefulness? This is core

**Comment by syuhei176** [comment]
We can close this issue? I think we can open new concrete issue for parse ivy like lang. And its priority is not so high now.

https://scrapbox.io/cryptoeconimicslab/%E6%B5%81%E8%A1%8C%E3%82%8B%E3%82%B9%E3%83%9E%E3%82%B3%E3%83%B3%E8%A8%80%E8%AA%9E%E3%81%A8%E3%81%AF

**Comment by syuhei176** [comment]
moved to https://github.com/cryptoeconomicslab/chamber-lang
