### ISSUE TITLE
block explorer

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#70]
- Users can see block by block number
- Users can see transactions by block number
- Users can see transactions by owner?
- Users can see UTXOs by transaction id?
- Users can see UTXOs by owner?

**Comment by syuhei176** [comment]
first version of block explorer was deployed.
http://d26mjzcg4v6n3c.cloudfront.net/explorer

**Comment by shogochiai** [comment]
note:
Request to the ELB endpoint of Plasma is via http. And it causes error on brave browser
