### ISSUE TITLE
create pubsub API to send coin history

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#79]
## Description

In Plasma Cash, users should send the history of a coin when they transfer the coin to other people. Users also should do in Plasma Chamber.

I think it's available for creating multi-sig.
2 users sign the same transaction in multi-sig UTXO and also need confsig.
Users can use pub-sub channel on child chain.

Basically, we should send history directly to prevent the operator's withholding.
Are there easy ways to sent data from a user to other users?
@shogochiai

**Comment by shogochiai** [comment]
PubSub requires always-online property for all users. In the scenario op tries withholding, we might not continue payment in order to exit from childchain. So the PubSub requirement is not so much ideal or useful I guess.

**Comment by syuhei176** [comment]
> PubSub requires always-online property for all users. Given the scenario op tries withholding, we might not continue payment in order to exit from child chain. So the PubSub requirement is not so much ideal or useful I guess.

I think there are 2 steps.

1. The user tries to send history through operator
2. If the user detects withholdings(by the timeout of ack), the user tries to send directory.

> ... But wait, force include only reveals small history of the coin. And you are currently withholded the other history parts for payment completion. Liveness has been lost? If offline payment break Liveness property, Plasma Cash must be online (only for the history passing)

In transfer situation, a receiver doesn't receive a coin, until verifying all history of the coin.
The receiver need not challenge that coin, so liveness isn't lost.

**Comment by syuhei176** [comment]
In Exchange, Making multisig case, also liveness isn't lost, because users don't send confsig until verifying all history of the coin.

In refund or getting coin after winning multisig game case, also liveness isn't lost, because users sent all coin history before "making multisig" each other. Users get coin history during multisig by themselves from the operator.

**Comment by syuhei176** [comment]
@shogochiai How about launching MQTT server for first light implementation.
This is for sending proof and swap signs.
Users don't have to be online.

**Comment by syuhei176** [comment]
@shogochiai How do you think which is better for MQTT server embedded and another process?
ex)
use mosca in childchain. or user another MQTT server.
