### ISSUE TITLE
We can replace chamber's block to prime style

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#85]
## Description

We can replace chamber's SMT and UTXO to prime style to handle `amount`.

https://ethresear.ch/t/plasma-prime-design-proposal/4222?u=syuhei176

- Chamber's SMT to SMT and RSA accumulator
- All coin has segment.

current chamber's style

```
{
owners: [0x00ab....],
value: [12345, 12346],
state: [OwnState]
}
```

after style

```
{
owners: [0x00ab....],
value: [{begin:12345, end:123456}],
state: [OwnState]
}
```

**Comment by shogochiai** [comment]
Do you name slot as chunk?
