### ISSUE TITLE
Deposit multiple token types

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#92]
## Description

We wanna deposit multiple ERC20 tokens and ERC721 tokens.
Use merkle branch? or any other ideas?

https://ethresear.ch/t/plasma-prime-design-proposal/4222/5?u=syuhei176

**Comment by shogochiai** [comment]
maybe NFT is unsegmentable chunk?

**Comment by shogochiai** [comment]
If RSA accumulator works well, depth is gonna be so cheap resource.

**Comment by syuhei176** [comment]
Yeah, but another disadvantage is that we should define token types before launch plasma.

**Comment by shogochiai** [comment]
Let's say, of we need 1 million token types, additional depth would be 20.

Essentially what we need is dynamic length array which is filled with tree-of-chunk. And the maximal possible length of that array must be 1000000≒2^20.

This is why I am optimistic for 1M token types. We can solve it by cheap additional 20 depth.

**Comment by syuhei176** [comment]
Current design
`1` in Plasma is 1 wei.
SMT depth is 16.
So, the chunk size is `1000000000000000000`

### define constant values

sample

```
CHUNK_SIZE = 1000000000
UNIT_SIZE = 1gwei (=1eth / CHUNK_SIZE)
TOKEN_TYPES_DEPTH = 8(2^8 token types)
SMT_DEPTH = 16
total deposit per an asset = (2^SMT_DEPTH)*UNIT_SIZE
```

**Comment by syuhei176** [comment]
The feature added in these PRs.

https://github.com/cryptoeconomicslab/chamber-packages/pull/79
https://github.com/cryptoeconomicslab/chamber-packages/pull/80
